// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_YKQsg8kj0wxKYn0FVFwpCIBkknKHbqM',
    appId: '1:650360320649:web:1248a8d4e72be5897a4c58',
    messagingSenderId: '650360320649',
    projectId: 'smart-pick-8421f',
    authDomain: 'smart-pick-8421f.firebaseapp.com',
    storageBucket: 'smart-pick-8421f.firebasestorage.app',
    measurementId: 'G-G318Q6PHXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDefSr-2qxYSYnOTObNE9G_fvB5rvdqIME',
    appId: '1:650360320649:android:af1cf8955698c68b7a4c58',
    messagingSenderId: '650360320649',
    projectId: 'smart-pick-8421f',
    storageBucket: 'smart-pick-8421f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrw_sLVTt6vBkav3pjPkmtt6TKPuvviEc',
    appId: '1:650360320649:ios:0ce5d541f654bc717a4c58',
    messagingSenderId: '650360320649',
    projectId: 'smart-pick-8421f',
    storageBucket: 'smart-pick-8421f.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceapp',
  );
}
